### ISSUE TITLE
Async/exclusive tests

### ISSUE THREAD

**Issue by dy** [grahamlyons/tst#1]
Hello, Graham!

Recently I started thinking about minimalistic test runner for both browser/node and stumbled upon your package, which is I think very nice, comparing to the huge ones like [mocha](https://www.npmjs.com/package/mocha), [ava](https://www.npmjs.com/package/ava), [tap](https://www.npmjs.com/package/tap), [tape](https://www.npmjs.com/package/tape) etc. Almost exactly the thing I wanted to do.
Two features stops me from switching to `tst`: exclusive and async tests. They are a well-established practice and convention, and also essential part of my workflow. It is impossible to delegate them to side packages, they have to be the part of test runner.
I can implement this, in tap-compatible way:
`test.skip()`, `test.only()` and `test.end()`. But that will make `test` function async (like in mocha, tape or ava), which is I beleive not really important (what are the use-cases to log outside of the tests and bind that to testing flow?), thoght [some other guys don’t think so](https://github.com/isaacs/node-tap/issues/187), which seems to be an interest in theoretical purity rather than usability.
This issue is just to check whether you react on issues and whether you’re open to contributions :)

Thank you and looking forward!
@grahamlyons

**Comment by dy** [comment]
@grahamlyons so does it mean you don’t check issues and I should write my own implementation :(?

**Comment by grahamlyons** [comment]
@dfcreative, no I'm just on holiday at the moment so I haven't got around to replying to this.

I'm active on Github and I'm very happy to consider pull requests.

**Comment by dy** [comment]
@grahamlyons ok, here is the first one #2

**Comment by dy** [comment]
@grahamlyons hi! Sorry for disturbing, but I kind of need this updated package in development.
Do you have any opportunity to look at it?

**Comment by grahamlyons** [comment]
Hi @dfcreative, I'm still on holiday at the moment but I'll be back in front of my computer tomorrow. I'll look at this more closely then.

**Comment by dy** [comment]
@grahamlyons  Ok, thank you. https://www.npmjs.com/package/tst
But still If you don’t mind I’ll keep the original authorship.

**Comment by grahamlyons** [comment]
@dfcreative, that's fine by me. Have fun with it. I even opened a pull request on your new module!
